spring.application.name=sliderplace
spring.datasource.url=jdbc:mysql://localhost:3307/sliderplaces
spring.datasource.username=root
spring.datasource.password=rosniak123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always